plugins { id 'com.android.application' }

android {
    namespace 'com.yuen.nativejpocr'
    compileSdk 35
    defaultConfig {
        applicationId "com.yuen.nativejpocr"
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName "0.4.0"
    }
    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.mlkit:text-recognition-japanese:16.0.1'
}
